/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gmail_kunicins_olegs_libshout_Libshout */

#ifndef _Included_com_gmail_kunicins_olegs_libshout_Libshout
#define _Included_com_gmail_kunicins_olegs_libshout_Libshout
#ifdef __cplusplus
extern "C" {
#endif
#undef com_gmail_kunicins_olegs_libshout_Libshout_SUCCESS
#define com_gmail_kunicins_olegs_libshout_Libshout_SUCCESS 0L
#undef com_gmail_kunicins_olegs_libshout_Libshout_CONNECTED
#define com_gmail_kunicins_olegs_libshout_Libshout_CONNECTED -7L
#undef com_gmail_kunicins_olegs_libshout_Libshout_FORMAT_OGG
#define com_gmail_kunicins_olegs_libshout_Libshout_FORMAT_OGG 0L
#undef com_gmail_kunicins_olegs_libshout_Libshout_FORMAT_MP3
#define com_gmail_kunicins_olegs_libshout_Libshout_FORMAT_MP3 1L
#undef com_gmail_kunicins_olegs_libshout_Libshout_PROTOCOL_HTTP
#define com_gmail_kunicins_olegs_libshout_Libshout_PROTOCOL_HTTP 0L
#undef com_gmail_kunicins_olegs_libshout_Libshout_PROTOCOL_XAUDIOCAST
#define com_gmail_kunicins_olegs_libshout_Libshout_PROTOCOL_XAUDIOCAST 1L
#undef com_gmail_kunicins_olegs_libshout_Libshout_PROTOCOL_ICY
#define com_gmail_kunicins_olegs_libshout_Libshout_PROTOCOL_ICY 2L
/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1shutdown
  (JNIEnv *, jclass);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_version
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1version
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_get_error
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1get_1error
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_get_errno
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1get_1errno
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_get_connected
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1get_1connected
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_set_host
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1set_1host
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_get_host
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1get_1host
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_set_port
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1set_1port
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_get_port
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1get_1port
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_set_password
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1set_1password
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_get_password
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1get_1password
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_set_mount
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1set_1mount
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_get_mount
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1get_1mount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_set_name
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1set_1name
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_get_name
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1get_1name
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_set_url
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1set_1url
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_get_url
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1get_1url
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_set_genre
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1set_1genre
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_get_genre
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1get_1genre
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_set_user
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1set_1user
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_get_user
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1get_1user
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_set_agent
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1set_1agent
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_get_agent
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1get_1agent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_set_description
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1set_1description
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_get_description
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1get_1description
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_set_dumpfile
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1set_1dumpfile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_get_dumpfile
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1get_1dumpfile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_set_audio_info
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1set_1audio_1info
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_get_audio_info
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1get_1audio_1info
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_set_public
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1set_1public
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_get_public
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1get_1public
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_set_format
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1set_1format
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_get_format
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1get_1format
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_set_protocol
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1set_1protocol
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_get_protocol
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1get_1protocol
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_set_nonblocking
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1set_1nonblocking
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_get_nonblocking
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1get_1nonblocking
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_open
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1open
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_close
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_send
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1send
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_send_raw
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1send_1raw
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_queuelen
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1queuelen
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_sync
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1sync
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_delay
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1delay
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_metadata_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1metadata_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_set_metadata
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1set_1metadata
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_metadata_add
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1metadata_1add
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_gmail_kunicins_olegs_libshout_Libshout
 * Method:    shout_metadata_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gmail_kunicins_olegs_libshout_Libshout_shout_1metadata_1free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
